### ISSUE TITLE
Sap library

### ISSUE THREAD

**Issue by JavierRodriguezPrieto** [SAP/bayesian-network-builder#1]
Hello,

When i create my project and add sap library dependency says:

[info] Resolved  dependencies
[warn]
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.sap:bnb:0.1
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/sap/bnb/0.1/bnb-0.1.pom
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:2

Where is this library? or can you tell me a resolver?

Thanks

**Comment by gfrison** [comment]
hi, it is not yet published on a public repository.
What you can do now is to clone it and run 
sbt publishLocal
and it is available on your local repo.

**Comment by gfrison** [comment]
I will publish it in a public repo.

**Comment by JavierRodriguezPrieto** [comment]
Thanks Giancarlo,

I had an issue in windows because i have an space in the folder of my user and is not getting correctly, so i had to move the library .ivy2 files to other folder in sbtconfig.txt.

Its working perfectly fine!
